<!-- greetings -->
<section class="top-150">
    <div class="container" data-aos="fade-up" data-aos-delay="100">
        <h1 class="fs-3 fw-bold text-uppercase text-center mb-5">Terimakasih Telah Mengunjungi Dokter Rumah</h1>
        <p class="mb-3"><a href="#" class="fst-italic fw-bold a-color">Dokterrumah.com</a> adalah Konsultan arsitek yang bergerak di Jasa Desain Rumah serta fokus pada pembuatan perencanaan bangunan hunian dan komersial. Kami membantu perencanaan / mendesain banguanan renovasi atau bangun baru. Untuk memenuhi visi kami, Jasa Arsitek Rumah kami disiplin untuk terus meningkatkan kualitas prduk, enjoy di bidang yang dikerjakannya, selalu openmind, <span class="fw-bold fst-italic">PASSIONATE</span> dan mengerjakan desain dengan sepenuh hati.</p>
        <p class="mb-3"><a href="#" class="fst-italic fw-bold a-color">Dokterrumah.com</a> adalah perusahaan / kantor arsitek yang menyediakan jasa arsitek profesional untuk jasa desain rumah mewah, jasa desain perumahan ataupun jasa desain bangunan komersil seperti jasa desain villa eksekutif, desain cluster perumahan elit, desain perumahan mewah, perumahan minimalis, desain apartemen, desain hotel berbintang, desain resort mewah, desain rumah bergaya luar negeri, dll.</p>
        <p class="mb-3"><a href="#" class="fst-italic fw-bold a-color">Dokterrumah.com</a> menyediakan layanan Jasa Arsitek Rumah Mewah, Arsitek Rumah Minimalis / Desainer Rumah Minimalis, Desain Rumah Modern, Rumah Klasik, Tropis, Industrial, Mediterian, American, Moroccan, Scandinavian,dll. Kami juga mendesain berbagai model rumah tumbuh, desain rumah 1 lantai, desain rumah 2 lantai, desain rumah 3 lantai ataupun desain rumah 4 lantai.</p>
        <p class="mb-3"><a href="#" class="fst-italic fw-bold a-color">Dokterrumah.com</a> sebagai desainer rumah dan jasa desain bangunan mewaj berkantor di Malang dapat melayani jasa desain bangunan secara offline ataupun 100% online. Jasa deain rumah online mencakup seluruh Indonesia dan bahkan sampai mancanegara. Kini, <a href="#" class="fw-bold fst-italic a-color">Dokterrumah.com</a> juga menyediakan jasa desain dalam rumah atua jasa desain interior untuk hunian Anda.</p>
        <p class="mb-3">Properti bai kitu rumah atau bangunan komersil adalah investasi jangka panjang dan bernilai sangat besar. Tanpa perencanaan yang tepat, dapat membuat kerugian besar dan bahkan penyesalan seumur hidup. Dengan semakin berkembangnya perekonomian suatu negara, maka harga rumah dan harga perumahan akan semakin meningkat setiap waktu seiring dengan pertumbuhan jumlah permintaan. Maka, sudah saatnya Anda merencanakan hunian impian Anda bersama <a href="#"class="fw-bold fst-italic a-color">Dokterrumah.com</a>. Semakin cepat, semakin bagus sebelum harga bahan bangunan dan properti naik.</p> 
    </div>
</section>